address: '127.0.0.1:8899'       # self ip:port address where api service will be alvalible
databases:                      # list currently avalible databases
    - database-sqlite:                 # internal database service name
        name: 'database'        # database instance name
        type: sqlite            # the type of the dattabase
        path: 'database.sqlite' # path / ip:pot to the database file / host 
        user: root              # database access user
        pass: root              # database access password
    - database-sqlite1:                 # internal database service name
        name: 'database1'        # database instance name
        type: sqlite            # the type of the dattabase
        path: 'database22.sqlite' # path / ip:pot to the database file / host 
        user: root              # database access user
        pass: root              # database access password
    # - new-database:
    #     name: 'new-database'
    #     type: mysql
    #     path: '127.0.0.1:3306'
    #     user: root
    #     pass: root
